### ISSUE TITLE
01 - 03 - All Cards On Deck

### ISSUE THREAD

**Issue by aksnell** [aksnell/assignments#3]
In this project, you will use C# to model [a deck of playing cards](https://en.wikipedia.org/wiki/standard_52-card_deck). You'll also add functionality such as shuffling and dealing.

### Shuffling Cards

As we have seen, computers do _exactly_ what we tell them to do. Thus, computers are bad at generating truly random numbers. Randomness is a deep and complex topic, but it's worth pointing out that most random numbers we use in computing are what we call "[pseudorandom](https://en.wikipedia.org/wiki/pseudorandomness)". That is, they generate numbers that appear to be random such that _guessing_ the next random number the computer's fixed algorithm is going to generate is very difficult. This makes it _good enough_ for most purposes. For this assignment, you will read about, then implement, a popular algorithm that shuffles the order of a finite set using C#'s built-in `Random.Next()` function as a pseudorandom number generator.

## Objectives

- Demonstrate usage of arrays to model resources.
- Understand and implement algorithms.
- Understand loops.

## Requirements

- Your deck should contain 52 unique cards.
- All cards should be represented as as string such as "Ace of Hearts"
- There are four suits: "Clubs", "Diamonds", "Hearts", and "Spades".
- There are 13 ranks: "Ace", "2", "3", "4", "5", "6", "7", "8", "9", "10",
  "Jack", "Queen", and "King".

You will model these in code, in any way you see fit. It may require you to experiment and try several techniques. There are _many_ valid solutions.

> NOTE: The more you plan this out (focus on the _algorithm_) the better you will do.

To shuffle the cards, you should implement the [Fisher–Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) algorithm. The shuffling algorithm starts with the last element in our collection (in our case a deck of cards) and swaps it with a randomly selected element that comes before it. This continues downward through the elements towards the first element. Watch the first few minutes [of this video](https://www.youtube.com/watch?v=tLxBwSL3lPQ) for a visual description of the algorithm.

If we were going to write an _algorithm_ for this we would write something like:

```
make n = 52 since we are dealing with 52 elements

for firstIndex from n - 1 down to 1 do:
  secondIndex = random integer that is greater than or equal to 0 and LESS than firstIndex

  Now swap the values at firstIndex and secondIndex by doing this:
    firstValue = the value from items[firstIndex]
    secondValue = the value from items[secondIndex]
    items[firstIndex] = secondValue
    items[secondIndex] = firstValue
```

_hint:_ understand the algorithm before you try to implement it.

### Explorer Mode

- [x] Once the program starts, you should create a new deck.
- [x] After deck creation, you should shuffle the deck.
- [x] After the deck is shuffled, display the top two cards.

## Adventure Mode

- [ ] In addition to displaying the top two cards, also store these two "dealt" cards in a variable named `playerHand`. Consider what _type_ of variable `playerHand` will have to be.
- [ ] Implement a way to deal cards into two _different_ hands.

## Epic Mode

- [ ] Implement the game of [War][1]

[1]: https://en.wikipedia.org/wiki/War_(card_game)

## Resources

- [List](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netcore-3.1)

**Comment by aksnell** [comment]
https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs
I will be coming back for Epic Mode, that sounds fun.

**Comment by gstark** [comment]
Amazing work. I'm going to give you some deep feedback since you did such great work here. These are all areas where you can work to get your code to follow a better C# convention as well as be more generalized.  You clearly have some experience in other languages. Now you get to work on learning a new language and adapting your style to how this language works.

1. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L8 and https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L13

Leave out the `4` in the definition. C# can figure out the length of the array.

2. Using a `byte` here isn't the best choice. Just use the `string` type you used for the `Face` and `Suit` - https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L34 Since they were good data type choices for your array of options, they are good choices here for the class properties.

3. The `ID` is never really used and serves no purpose. All the bit-shifting magic isn't useful here. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L36-L40

4. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L46 - I would not suggest overriding `ToString` without a good cause. It isn't a bad idea, but I think a better method name is `Description` or `DisplayString` -- When we start overriding core class methods we can introduce unexpected behavior.

5. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L53-L56 - Don't use the arrays, use a `List<Card>` -- it will not have any of the restrictions you are finding C# arrays have.

6. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L62 - and https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L64 - Let the language figure out the length

7. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L82 - I will not allow you to use variables named `i` -- At least use `index` or `cardIndex` -- using single variable names can be a lazy habit. 

8. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L83 - Same thing. What is `x` -- why is this variable named `x`? Does `x` mean something in this problem? How does `x` relate to shuffling or to cards, or to a deck. I think you mean `randomIndex` or `randomSwapIndex`, etc.

9. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L82 do not hard code the 51. Use the length of the deck. What happens if we change the requirement to have a double deck? You'd have to run around the code looking for all the places you put `52` and `51` in your code.

10. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L88 Remove debugging code before you turn in your work.

11. Again, we can make a better choice of method name and variable names. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L95 - `ShowTopCards(int numberOfCardsToShow)` - this is far more expressive.

12. https://github.com/aksnell/sdg/blob/master/lessons/three/DeckOfCards/Dealer.cs#L99 - No more `i` variables. Also using `!=` is unexpected here. It is more conventional to use `<` or `<=` in a for loop like this.

Also leave a minimum of ONE blank line between method definitions. And between paragraphs of code.

![sdg 2020-05-14 08-22-37](https://user-images.githubusercontent.com/2607/81933957-27a90500-95bc-11ea-8e44-14848622c9bc.png)

**Comment by aksnell** [comment]
Your homework **01 - 03 - All Cards On Deck** was marked: **Exceeds Expectations**

![Wow!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBZQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9952cb840c48f59dd527f49738e09debc2144c20/8376B176-72B1-41DE-8C04-D8DBC1E04E39.MOV)
> &ldquo;Wow!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/85)**__

**Comment by aksnell** [comment]
@gstark 

I genuinely appreciate this! I have been programming for maybe five years as a completely solitary, hobbyist thing. I have never had any source feedback so I ended up being drawn to looking into more theoretical knowledge I could learn that for myself and less practical implementation, which is far more important for an actual career I think between repl.it and GitHub I have maybe two projects that actually became practically functional for myself. I usually just end up rewriting and re-implementing something over and over as my interest shifts and never actually get anything done.

I agree with all of your recommendations, though giving up single letter loop variables will be a challenge. C# and Java are my biggest language blind spots because I usually prefer a more functional style of programming to OO... and its hard to get more OO than those two. I also never fully understood the voodoo behind the dotnet runtime   @@beyond some people being very adamant that its not really a VM or byte machine despite all appearance and it didn't feel right to use a language when I didn't even know how it ran. So when it comes to writing C# I am ignorant of even basic idioms and conventions.

I will say just for my sense of pride that I absolutely know that the ID field is not doing anything there. I just left it in to make fun of myself for planning out and pre-optimizing for a task that never came because I refused to just go slowly and read. I also realized that it wouldn't of worked anyway, and would have produced duplicate IDs because obviously the transitive property and basic math.
