### ISSUE TITLE
02-03 Jurassic Park - 

### ISSUE THREAD

**Issue by aksnell** [aksnell/assignments#6]
In this assignment, you will be creating a console application that manages a zoo
full of dinosaurs.

## Objectives

- Practice control structures.
- Practice data structures.
- Practice working with user data.
- Practice with LINQ.
- Practice with OOP concepts.

## Requirements

- Create a console application that manages the dinosaurs in your zoo.

### Explorer Mode

- [x] Create a class to represent your dinosaurs. The class should have the following properties

  - [x] `Name`
  - [x] `DietType` - This will be "carnivore" or "herbivore"
  - [x] `WhenAcquired` - This will default to the current time when the
        dinosaur is created
  - [x] `Weight` - How heavy the dinosaur is in pounds.
  - [x] `EnclosureNumber` - the number of the pen the dinosaur is currently in

- [x] Add a method `Description` to your class to print out a description of the dinosaur to include all of its properties. Create an output format of your choosing.
- [x] Your dinosaurs will be stored in a `List<Dinosaur>`.
- [x] When the console application runs, it should let the user choose one of the following actions:
  - [x] `View`
    - This command will show the all the dinosaurs in the list, ordered by `WhenAcquired`
  - [x] `Add`
    - This command will let the user type in the information for a dinosaur and add it to the list
  - [x] `Remove`
    - This command will prompt the user for a dinosaur name then find and delete the dinosaur with that name.
  - [x] `Transfer`
    - This command will prompt the user for a dinosaur name and a new `EnclosureNumber` and update that dino's information.
  - [x] `Summary`
    - [x] This command will display the number of carnivores and the number of herbivores.
  - [x] `Quit`
    - [x] This will stop the program

### Adventure Mode

- [x] Add an option to view the Dinosaurs acquired after a given date (to be given by the user).
- [x] Add an option to view all the Dinosaurs in a given enclosure number.

### Epic Mode

- [x] Learn how to read and write from a file. At the start of the program load all the dinosaurs from a file. When the program ends write out all the dinosaurs to the same file.

**Comment by aksnell** [comment]
https://github.com/aksnell/jurassic-park

mvp

**Comment by aksnell** [comment]
I went ahead and massively over engineered it in tribute to your lecture today to complete Epic mode.

Full MVC, logging with two levels and a debug flag, load and save from a json file, its just a hot mess.

For reference, 

https://github.com/aksnell/jurassic-park/tree/f726a1bc3b313221d67379278e2c4d84e1a68a84

Was my very different, much saner explorer mode solution.

**Comment by gstark** [comment]
This code is based on the link you submitted.

I am going to reject this homework and highly recommend you fix these issues.

I am then going to post for you another review of your "hot mess" code.

I'm not going to let you submit and persist code considered a "hot mess" -- it won't work for you when you submit code for job applications, and it won't be acceptable on a team.

Now is not the time to practice tricky stuff and code that is "hot mess" -- this is a time for you to practice writing simple, solid, clean, and working code.

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L35-L37
- Why make your life hard. What if the name has two spaces in it?
- This is just bad User Experience
- **UNDO THIS** and make it better

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L37
- See splitting the array causes you to have bad variable names. If you were going to do this you should make individual and better variable names for each element.
```
var name = newDinoArgs[0]
var diet = newDinoArgs[1]
```
- This way if you reorder the input you have *one* place to change the indexes.

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L77
- This doesn't actually remove the dino

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L86
- Again, what about dino's that have a space in their name?

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L97
- I do not believe you need `ToList` here

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L106-L107
- Nope, not letting you submit code with these variable names. Justify to me why `carn` is a better variable name than `carnivores` or `carnivoreCount`

https://github.com/aksnell/jurassic-park/blob/f726a1bc3b313221d67379278e2c4d84e1a68a84/Program.cs#L116
- This doesn't actually print anything

**Comment by aksnell** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Unacceptable**

![I'm just gonna...](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--354ad6ba2ab2a53888555f9ec77d2db94e87586c/nope.gif)
> &ldquo;I'm just gonna...&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/20)**__

**Comment by aksnell** [comment]
https://github.com/aksnell/jurassic-park

I wont stand for this slander :smile: 

Please :dagger:  my master branch instead, there are some _slight_ differences.

**Comment by gstark** [comment]
Try to ween yourself from abbreviations: https://github.com/aksnell/jurassic-park/blob/master/Program.cs#L15 -- I mn every1 lvs a good abbr. Do you agr? Code wrtn that wy is rlly ez 2  _stand

Nice logging class. Now try using the built in .NET logging facility: https://thecodebuzz.com/logging-in-net-core-console-application/

https://github.com/aksnell/jurassic-park/blob/master/Controllers/DinoController.cs -- Interesting. Most of the actual behavior is really in the `Park` class.

This is a premature optimization: https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L21 -- And is indicated that you have to *special case* the version where no `thunk` is given. This is fancy code for fancy sake and must be *UNFACTORED* -- unless this pattern appears many more times in the code it is better to repeat that short bit of code rather than have this fancy code that has to special case things.

This should be in it's own file: https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L81

No blank space here: https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L83 -- and here: https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L103 -- and here -- https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L105 -- and here https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L9 -- and here https://github.com/aksnell/jurassic-park/blob/master/Models/Park.cs#L12 -- if anything at the top of the scope of a namespace or class, it could have some comments of documentation.

Names: https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L14

`for(var dino in dinos)` -- unless you need a specific parent class: https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L26

`foreach(var choice in choices)` -- https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L44

https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L63 -- recursion is the wrong tool here. C# is not tail recursive aware so it is the wrong tool for the job.

Whitespace: https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L72

https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L81 -- wouldn't you, given your own reasoning, still want to check that? You can declare 32 bit integers, but you'd still want to check, no?

No need for generics. Why not just return a `DateTime` from this method?

Whitespace before: https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L128 and https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L138 and https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L139 and https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L152 and https://github.com/aksnell/jurassic-park/blob/master/Views/DinoView.cs#L161 etc...

This `View` method on DinoController is hiding real implementation. So you have effectively squashed multiple methods into one, but then you have to pass it the name of what you want. It is the equivalent of this:

```
public string AbstractThing(string nameOfThing)
{
    switch(nameOfThing)
   {
       case "Name":  return Name;
       case "Size": return Size;
   }
}
```

instead of

```
public String Name() { return Name; }
public String Size() { return Size; }
```

So I the reader of your code have to think about the fact that `View` has *DIFFERENT BEHAVIOR* based on what string I pass as the first argument. *AND* I lose all of the language introspection and refactoring tools since you've _hidden away_ real methods behind a fancy switch statement inside one method.  Again this feels like a fancy code implementation just for the purpose of being fancy. *BREAK THESE INTO METHODS*

I get the sense you like to mess around with different techniques. The fact that you are trying to cram 5 different behaviors into one method and dynamically dispatch them reinforces that.

I do _strongly_ suggest that you resist the temptation for fancy implementation things and build a strong habit of simple, neat, idiomatic code.  Once you have proven that on a continuous basis you are free to implement an assignment in a nice clean way and then go back and refactor it into advanced techniques. I'm open and willing to discuss _WHICH_ technique you should be practicing rather than have you stab around at various things that we then need to discuss here in an assignment review.

Also, make sure you have the OmniSharper extension installed and it is set to format your code on save. I'd like to ensure you are using it to do basic formatting and alignment of your code.

**Comment by aksnell** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Exceeds Expectations**

![You got it!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2c38988a8a66323675b11efd93094c28cccadde/cat%20rainbow.gif)
> &ldquo;You got it!&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/15)**__
