### ISSUE TITLE
02 - 03 - First Bank of Suncoast - 

### ISSUE THREAD

**Issue by aksnell** [aksnell/assignments#7]
For this assignment, you will be creating your own personal bank account manager. You will be creating an app that will let you track both a savings account and a checking account total by performing transactions, such as withdrawals, deposits, and transfers. The application will also save your information in a file so you can track your account totals over time.

## Objectives

- Practice control structures.
- Practice data structures.
- Practice working with user data.
- Practice with LINQ.
- Practice with OOP concepts.
- Practice working with files.

## Requirements

Create a console app that allows a user to manage a banking account.

As user should be able to make transactions against their accounts.

The transaction information should be stored in a file, using a `CSV`(or `JSON`) format to record the data.

Balances will be computed by determining the cumulative effect of all the transactions in order. For instance, if a user deposits 10 to their savings account and then withdraws 8 from their savings account, their balance is computed as 2.

### Explorer Mode

- [x] The app should load past transactions from a file at start up.
- [x] As a user I should be able to see the balances in my saving and checking account when the program first starts.
- [x] Never allow withdrawing or depositing more money than allowed. That is, we cannot allow our accounts to go negative.
- [x] When prompting for an amount to deposit or withdraw always ensure the amount is positive.
- [x] As a user I should be able to deposit funds to my savings account.
- [x] As a user I should be able to deposit funds to my checking account.
- [x] As a user I should be able to withdraw funds from my savings account.
- [x] As a user I should be able to withdraw funds from my checking account.
- [x] As a user I should be able to see my account balances.
- [x] The app should, after each transaction, write all the transactions to a file using a standard format.

### Adventure Mode

- [x] Add the ability to transfer funds from my checking account to my savings account.
- [x] Add the ability to transfer funds from my savings account to my checking accounts.
- [x] Add the ability to have multiple users. There are many steps to take here, so take the time to plan out the changes needed. This includes changes to the interface as well as changes to how you store the data.

### Epic Mode

- [x] Add simple password protection to your user's accounts

## Additional Resources

- .NET

  - [.NET Documentation](https://docs.microsoft.com/en-us/dotnet/)

  - [CsvHelper](https://joshclose.github.io/CsvHelper/getting-started)

**Comment by aksnell** [comment]
https://github.com/aksnell/suncoast-bank

**Comment by aksnell** [comment]
Oh. and I know I should be appending to files rather than purely overwriting, I will look that up tomorrow at some point.

**Comment by aksnell** [comment]
https://github.com/aksnell/suncoast-bank/tree/dev

Significantly re-worked dev branch, only slightly more complicated.

My goals for reworking were,

- Classes are more defined, single responsibility, split off three classes from the Bank class.
- new Portal class for managing account creation, storage, and logging in,
- new Account class for managing passwords, and verification.
- new Front end class just to strip out those functions.
- Bank class is now BankConnection, much smaller, only handles transaction details after the Portal class says its okay.
- All classes now only handle user input from one method.
- My joke hash function is still a joke, but now its a a technically working one. Xoring every character in a string is obviously cryptographically secure, and absolutely won't eventually blow up the csv file with a bad output.
- Messing around with pseudo enums (used structs because enums are not implicitly cast like struct fields are, at least according to stackoverflow) for control flow and error handling simply because I honestly don't know how to do error handling in C# until we cover it, and I like treating errors as simple values. However, I didn't go full golang and start explicitly writing out (if err != nil)... but I wanted to.

**Comment by gstark** [comment]
Do you need this default constructor? https://github.com/aksnell/suncoast-bank/blob/master/Account.cs#L13

If you don't need to access these from outside remove the get: https://github.com/aksnell/suncoast-bank/blob/master/Account.cs#L10-L11 -- if you don't set them from outside you can remove the `get` and make them normal internal private properties.

https://github.com/aksnell/suncoast-bank/blob/master/Account.cs#L30 --
Never invent your own cryptography -- and use a recognized strong algorithm when you can. I suggest checking out https://github.com/BcryptNet/bcrypt.net

You can also make a "custom set" function where you can have `public string Password` and have a `set` method that really just assigns to the passwordhash and encrypted password. In essence making a _virtual_ property. One that isn't backed by a value but is instead a facade for setting the hashed password and salt.

Does a `Bank` really have one account ID? This really seems more like `Account` where your `Account` seems more like a `User` or `Person` or `Customer` -- names matter.

Ugh, magic numbers: https://github.com/aksnell/suncoast-bank/blob/master/Constants.cs#L5-L22 -- avoid these whenever possible.  If you must, I would suggest using an `enum` instead or just descriptive strings.  See enums: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum -- By using an enum you are passing around a specific type instead of masquarading things as `int`

Also use names from the problem domain. Banks don't call int UNDERFLOW and OVERFLOW, those are programming terms. Always code in the language of the problem. So OVERDRAFT and UNDERDRAFT. or OVERDRAFT_ATTEMPT and UNDERDRAFT_ATTEMPT.

https://github.com/aksnell/suncoast-bank/blob/master/Bank.cs#L148 00 https://github.com/aksnell/suncoast-bank/blob/master/Bank.cs#L158-L159

Here is a case where perhaps an inherited class does help. Rather than have to pass a transaction type perhaps there should be a `WithdrawTransaction` and a `DepositTransaction` and they can be managed more intelligently that way. Displaying, totalling, etc.

This line of code: https://github.com/aksnell/suncoast-bank/blob/master/Bank.cs#L168 cannot stand without explaining why you are doing fancy math. This is also a symptom of using magic numbers. Magic numbers beget magic implementation in your code. And this magic cannot stand without explaining. Again, you are favoring fancy side effects.

https://github.com/aksnell/suncoast-bank/blob/master/Bank.cs#L192 - you don't need this else. When the `if` true part ends in a `return` there is no way to access the remaining code so you are free to not have an else and let that code flow freely.

Here is a perfect example where, if you had used subclasses you could have avoided a case statement. It even fits nicely the pattern of our child class "A WithdrawTransaction is a Transaction, a DepositTransaction is a transaction" - Try implementing the two types of transactions as inherited from a generic base class and see how that influences the design https://github.com/aksnell/suncoast-bank/blob/master/Bank.cs#L228


This is a comment that adds nothing to the context of the code. https://github.com/aksnell/suncoast-bank/blob/master/FrontEnd.cs#L36 Either improve the comment or get rid of it.

Here is another hint that this `Account` class is really a `User` -- `userAccount` as a variable name: https://github.com/aksnell/suncoast-bank/blob/master/Portal.cs#L35

**Comment by gstark** [comment]
This code style here is improved from the previous code. There is still some "fancy for fancy sake", e.g. the `^ 1` code. So I commend you for working on simplifying things. Try some of the above suggestions.

**Comment by aksnell** [comment]
Your homework **02 - 03 - First Bank of Suncoast - ** was marked: **Exceeds Expectations**

![Woooooh!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51a35f0aa3861c6c972e89ad3572a7cc7ad26dba/exceeds-1.gif)
> &ldquo;Woooooh!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/63)**__

**Comment by gstark** [comment]
Also be more careful with the spelling and meaning of commits. This commit message doesn't match what the commit actually does: https://github.com/aksnell/suncoast-bank/commit/a9542bf74571cd4e10b54ac4858c8d604b3c8209

**Comment by gstark** [comment]
So it does look like CsvReader uses C#'s built-in introspection to find the appropriate constructor. So if you name the constructor arguments after the matching column (and property) names then it will find and use it.

Here is some sample code I wrote to see how the introspection works:

```
using System;

namespace SuncoastBank
{
    class Program
    {
        static void IntrospectConstuctors()
        {
            Console.WriteLine("---- Introspect constructors ----");
            var constructors = typeof(Transaction).GetConstructors();

            foreach (var constructor in constructors)
            {
                Console.WriteLine(constructor.Name);
                foreach (var parameter in constructor.GetParameters())
                {
                    var type = parameter.GetType();
                    var name = parameter.Name;

                    Console.WriteLine($"    Parameter named {name} is type {type}");
                }
            }
        }

        static void Main(string[] args)
        {
            IntrospectConstuctors();

            var portal = new Portal();
            portal.Login();
        }
    }
}
```
